# Generated by Django 5.0.3 on 2024-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=10),
        ),
    ]
