# Generated by Django 5.0.3 on 2024-03-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagment', '0005_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
