# Generated by Django 5.0.3 on 2024-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagment', '0009_alter_borrowedbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='borrower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
