# Generated by Django 5.0.3 on 2024-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0002_remove_customuser_user_type_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Admin'), ('SA', 'SuperAdmin')], default='S', max_length=10),
        ),
    ]
