# Generated by Django 5.0.3 on 2024-03-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='is_returned',
            new_name='returned',
        ),
    ]
